services:
  java_app:
    build: ./Dockerfile-jar
    image: yuraigle/adrift-jar:latest
    container_name: adrift-jar
    ports:
      - "8085:8080"
    volumes:
      - ./adrift.sqlite:/adrift.sqlite
  web_app:
    build: ./Dockerfile-webapp
    image: yuraigle/adrift-nginx:latest
    container_name: adrift-nginx
    ports:
      - "8086:80"
